trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  gh_user_source_code: hugolmn
  gh_repo_source_code: garanse
  gh_user_build: garanse
  gh_repo_build: garanse.github.io
  gh_pass: $(gh_pat)
  gh_email: $(email)
  
steps:
- checkout: none
  persistCredentials: false

# Importation of git repositories
- script: git clone "https://$(gh_pat)@github.com/$(gh_user_source_code)/$(gh_repo_source_code).git" source_code
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Git] Clone Github pages source code repository"

- script: git clone "https://$(gh_pat)@github.com/$(gh_user_build)/$(gh_repo_build).git" build
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Git] Clone Github pages built website repository"

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  
- script: python -m pip install --upgrade pillow
  displayName: 'Install tools'

- script: python source_code/assets/images/generate-images.py
  workingDirectory: $(Build.StagingDirectory)
  displayName: 'Resizing new images'

# Setting up Ruby & Jekyll
- task: UseRubyVersion@0
  displayName: '[Ruby] Use Ruby >= 2.5'

- script: gem install bundler
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Jekyll] Install Bundler"

- script: |
    cd source_code
    bundle install
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Jekyll] Install dependencies"

# Building the website
- script: |
    cd source_code
    bundle exec jekyll build
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Jekyll] Build website"

- script: |
    cd build
    rm -rf *
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Git] Removing previous build"

- script: mv source_code/_site/* build/
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Git] Moving new build to build folder"

- script: |
    cd source_code
    git config user.email $(gh_email)
    git config user.name $(gh_user_source_code)
    git add .
    git commit -m "Azure pipeline updated source code"
    git push "https://$(gh_user_source_code):$(gh_pass)@github.com/$(gh_user_source_code)/$(gh_repo_source_code).git" master
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Push source_code'

- script: |
    cd build
    git config user.email $(gh_email)
    git config user.name $(gh_user_source_code)
    git add .
    git commit -m "Azure pipeline automatic build"
    git push "https://$(gh_user_source_code):$(gh_pass)@github.com/$(gh_user_build)/$(gh_repo_build).git" master
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Push new build'